// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookResponce struct {
	Message string               `json:"Message"`
	Error   bool                 `json:"Error"`
	Data    []*FetchBookResponce `json:"data"`
}

type ExcelUserResponce struct {
	Error   bool   `json:"Error"`
	Message string `json:"Message"`
}

type Fetch struct {
	Employeename string `json:"employeename"`
	Projectename string `json:"projectename"`
}

type FetchBlog struct {
	BlogText      string  `json:"blogText"`
	Videotopic    *string `json:"videotopic"`
	Bookname      *string `json:"bookname"`
	Toolname      *string `json:"toolname"`
	Referencelink *string `json:"referencelink"`
	Status        *bool   `json:"status"`
}

type FetchBlogInput struct {
	BlogID int `json:"BlogId"`
}

type FetchBookInput struct {
	ID     *int          `json:"ID"`
	Filter []*FilterBook `json:"Filter"`
}

type FetchBookResponce struct {
	BookName string `json:"book_name"`
	BookLink string `json:"bookLink"`
}

type FetchTool struct {
	Filter       *string `json:"Filter"`
	FilterColumn *string `json:"FilterColumn"`
}

type FetchToolData struct {
	Toolname *string `json:"toolname"`
	Toollink *string `json:"toollink"`
	IsActive *bool   `json:"is_active"`
}

type FetchToolsInput struct {
	ID     *int         `json:"ID"`
	Filter []*FetchTool `json:"Filter"`
}

type FetchVideo struct {
	VideoLink  string  `json:"video_link"`
	Paid       bool    `json:"paid"`
	VideoTopic string  `json:"videoTopic"`
	BookName   *string `json:"book_name"`
	ToolName   *string `json:"tool_name"`
	Status     bool    `json:"status"`
}

type FetchVideoInput struct {
	VideoID    *int    `json:"VideoId"`
	VideoTopic *string `json:"Video_topic"`
	Paid       *bool   `json:"paid"`
}

type FetchVideoResponce struct {
	Data []*FetchVideo `json:"data"`
}

type FilterBook struct {
	Filter       *string `json:"Filter"`
	FilterColumn *string `json:"FilterColumn"`
}

type MasterFetch struct {
	Error   bool              `json:"Error"`
	Message string            `json:"Message"`
	Data    []*MasterResponce `json:"Data"`
}

type MasterResponce struct {
	Video []*FetchVideo        `json:"Video"`
	Tool  []*FetchToolData     `json:"Tool"`
	Blog  []*FetchBlog         `json:"Blog"`
	Book  []*FetchBookResponce `json:"Book"`
}

type ResponceFetchBlog struct {
	Data []*FetchBlog `json:"data"`
}

type ToolResponceData struct {
	Data []*FetchToolData `json:"data"`
}

type UpdateBook struct {
	BookID   int     `json:"book_id"`
	BookName *string `json:"bookName"`
	BookLink *string `json:"bookLink"`
	Status   *bool   `json:"status"`
}

type UpdateTools struct {
	ToolID   int     `json:"tool_id"`
	ToolName *string `json:"toolName"`
	ToolLink *string `json:"toolLink"`
	Status   *bool   `json:"status"`
}

type UpdateVideo struct {
	VideoID    int     `json:"VideoId"`
	VideoLink  *string `json:"video_link"`
	Paid       *bool   `json:"paid"`
	VideoTopic *string `json:"videoTopic"`
	BookName   *string `json:"book_name"`
	ToolName   *string `json:"tool_name"`
	Status     *bool   `json:"status"`
}

type UpsertBook struct {
	BookName string `json:"bookName"`
	BookLink string `json:"bookLink"`
	Status   bool   `json:"status"`
}

type UpsertBookResponce struct {
	Message string `json:"message"`
}

type UpsertTool struct {
	ToolName string `json:"toolName"`
	ToolLink string `json:"toolLink"`
	Status   bool   `json:"status"`
}

type UpsertToolResponce struct {
	Message string `json:"message"`
}

type UpsertVideo struct {
	VideoLink  string  `json:"video_link"`
	Paid       bool    `json:"paid"`
	VideoTopic string  `json:"videoTopic"`
	BookName   *string `json:"book_name"`
	ToolName   *string `json:"tool_name"`
	Status     bool    `json:"status"`
}

type UpsertVideoResponce struct {
	Message string `json:"message"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type BlogResponce struct {
	Message string `json:"message"`
}

type Login struct {
	UserName *string `json:"userName"`
	Password *string `json:"Password"`
}

type LoginResponce struct {
	JwtToken *string `json:"JwtToken"`
}

type MasterExcelResponce struct {
	Error   bool   `json:"Error"`
	Message string `json:"Message"`
}

type UpdateUser struct {
	UserName    string  `json:"user_name"`
	OldPassword *string `json:"oldPassword"`
	Password    *string `json:"Password"`
	Email       *string `json:"email"`
	MobNo       *int    `json:"mob_no"`
	UserRole    *string `json:"user_role"`
	IsActive    *bool   `json:"is_active"`
}

type UpserBlogData struct {
	BlogText      string  `json:"blogText"`
	Videotopic    *string `json:"videotopic"`
	Bookname      *string `json:"bookname"`
	Toolname      *string `json:"toolname"`
	Referencelink *string `json:"referencelink"`
	Status        *bool   `json:"status"`
}

type UserResponce struct {
	Message string `json:"message"`
}

type UserUpsert struct {
	UserName string  `json:"user_name"`
	Password string  `json:"Password"`
	Email    *string `json:"email"`
	MobNo    *int    `json:"mob_no"`
	UserRole string  `json:"user_role"`
	IsActive bool    `json:"is_active"`
}
